### ISSUE TITLE
DataLevel not represented correctly

### ISSUE THREAD

**Issue by mcupak** [ga4gh/ADA-M#21]
In `master` (Proto3), `Header.resourceDataLevel` is of type `DataLevel.Level`, whereas in `develop`, it is of type `DataLevel`, which has a `level` property. This is a regression. Compare to how e.g. `RestrictionsUL` was translated.

**Comment by sdelatorrep** [comment]
Hi @mcupak . I see, I didn't notice I translated the same structure into 2 different things in Open API. 

For the sake of clarification, this structure in protobuf:
```
message Header {
  ...
  message DataLevel {
    enum Level {
      UNKNOWN     = 0; // Keep as the default value in case future versions add new DataLevels that old clients can't read
      DATABASE    = 1;
      METADATA    = 2;
      SUMMARISED  = 3;
      DATASET     = 4;
      RECORDSET   = 5;
      RECORD      = 6;
      RECORDFIELD = 7;
    }
  }
  ...
  DataLevel.Level resourceDataLevel             = 9;
  ...
}
```
was translated into OpenAPI as this:
```
  DataLevel:
    type: object
    required:
      - level
    properties:
      level:
        type: string
        enum: 
          - UNKNOWN
          - DATABASE
          - METADATA
          - SUMMARISED
          - DATASET
          - RECORDSET
          - RECORD
          - RECORDFIELD
```
However, in other fields with the same structure, e.g. RestrictionsUL, it was translated as this:
```
  RestrictionsUL:
    type: string
    enum:
      - UNRESTRICTED
      - LIMITED
```
which seems more accurate.
