### ISSUE TITLE
Typo: Header instead of header

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh/ADA-M#30]
The spec says:
```
components:
  schemas:
    Adam:
      type: object
      required:
        - Header
```
but it must be `header` (the name of the field starts with lowercase). 
If not, an OpenAPI viewer won't correctly identify the field as mandatory and won't show the `*` next to it:
![image](https://user-images.githubusercontent.com/17491353/51845780-7b84d180-2318-11e9-8652-f8b6567e21dc.png)
vs
![image](https://user-images.githubusercontent.com/17491353/51845815-8e97a180-2318-11e9-88b3-49c7c3d7390b.png)
